const products = [
  // Example product data
  {
    id: 1,
    name: "Apple",
    sku: "APL001",
    stock: 120,
    price: "0.99",
    returnRate: "2%",
    orders: 200,
    monthIncrease: "5%",
    yearIncrease: "10%",
  },
  {
    id: 2,
    name: "Banana",
    sku: "BNN002",
    stock: 150,
    price: "0.59",
    returnRate: "1.5%",
    orders: 180,
    monthIncrease: "3%",
    yearIncrease: "8%",
  },
  {
    id: 3,
    name: "Cherry",
    sku: "CHY003",
    stock: 90,
    price: "2.99",
    returnRate: "2.5%",
    orders: 75,
    monthIncrease: "4%",
    yearIncrease: "12%",
  },
  {
    id: 4,
    name: "Date",
    sku: "DAT004",
    stock: 50,
    price: "3.49",
    returnRate: "3%",
    orders: 50,
    monthIncrease: "2%",
    yearIncrease: "7%",
  },
  {
    id: 5,
    name: "Elderberry",
    sku: "ELD005",
    stock: 30,
    price: "1.99",
    returnRate: "1%",
    orders: 20,
    monthIncrease: "1%",
    yearIncrease: "3%",
  },
  {
    id: 6,
    name: "Fig",
    sku: "FIG006",
    stock: 60,
    price: "0.89",
    returnRate: "4%",
    orders: 100,
    monthIncrease: "6%",
    yearIncrease: "15%",
  },
  {
    id: 7,
    name: "Grape",
    sku: "GRP007",
    stock: 200,
    price: "0.79",
    returnRate: "1.8%",
    orders: 220,
    monthIncrease: "5%",
    yearIncrease: "10%",
  },
  {
    id: 8,
    name: "Honeydew",
    sku: "HND008",
    stock: 80,
    price: "1.29",
    returnRate: "2.2%",
    orders: 60,
    monthIncrease: "3%",
    yearIncrease: "9%",
  },
  {
    id: 9,
    name: "Ivy Gourd",
    sku: "IVG009",
    stock: 40,
    price: "4.99",
    returnRate: "2%",
    orders: 30,
    monthIncrease: "2%",
    yearIncrease: "11%",
  },
  {
    id: 10,
    name: "Jackfruit",
    sku: "JKF010",
    stock: 70,
    price: "1.49",
    returnRate: "3.5%",
    orders: 85,
    monthIncrease: "4%",
    yearIncrease: "14%",
  },
  {
    id: 11,
    name: "Kiwi",
    sku: "KIW011",
    stock: 120,
    price: "0.99",
    returnRate: "2%",
    orders: 150,
    monthIncrease: "5%",
    yearIncrease: "13%",
  },
  {
    id: 12,
    name: "Lemon",
    sku: "LEM012",
    stock: 160,
    price: "0.29",
    returnRate: "1%",
    orders: 200,
    monthIncrease: "3%",
    yearIncrease: "8%",
  },
  {
    id: 13,
    name: "Mango",
    sku: "MNG013",
    stock: 90,
    price: "0.79",
    returnRate: "2.5%",
    orders: 120,
    monthIncrease: "4%",
    yearIncrease: "12%",
  },
  {
    id: 14,
    name: "Nectarine",
    sku: "NCT014",
    stock: 110,
    price: "1.29",
    returnRate: "1.5%",
    orders: 95,
    monthIncrease: "2%",
    yearIncrease: "7%",
  },
  {
    id: 15,
    name: "Orange",
    sku: "ORG015",
    stock: 200,
    price: "0.59",
    returnRate: "1.8%",
    orders: 210,
    monthIncrease: "3%",
    yearIncrease: "9%",
  },
  {
    id: 16,
    name: "Papaya",
    sku: "PAP016",
    stock: 80,
    price: "1.99",
    returnRate: "3%",
    orders: 70,
    monthIncrease: "4%",
    yearIncrease: "10%",
  },
  {
    id: 2,
    name: "Banana",
    sku: "BNN002",
    stock: 150,
    price: "0.59",
    returnRate: "1.5%",
    orders: 180,
    monthIncrease: "3%",
    yearIncrease: "8%",
  },
  {
    id: 3,
    name: "Cherry",
    sku: "CHY003",
    stock: 90,
    price: "2.99",
    returnRate: "2.5%",
    orders: 75,
    monthIncrease: "4%",
    yearIncrease: "12%",
  },
  {
    id: 4,
    name: "Date",
    sku: "DAT004",
    stock: 50,
    price: "3.49",
    returnRate: "3%",
    orders: 50,
    monthIncrease: "2%",
    yearIncrease: "7%",
  },
  {
    id: 5,
    name: "Elderberry",
    sku: "ELD005",
    stock: 30,
    price: "1.99",
    returnRate: "1%",
    orders: 20,
    monthIncrease: "1%",
    yearIncrease: "3%",
  },
  {
    id: 6,
    name: "Fig",
    sku: "FIG006",
    stock: 60,
    price: "0.89",
    returnRate: "4%",
    orders: 100,
    monthIncrease: "6%",
    yearIncrease: "15%",
  },
  {
    id: 7,
    name: "Grape",
    sku: "GRP007",
    stock: 200,
    price: "0.79",
    returnRate: "1.8%",
    orders: 220,
    monthIncrease: "5%",
    yearIncrease: "10%",
  },
  {
    id: 8,
    name: "Honeydew",
    sku: "HND008",
    stock: 80,
    price: "1.29",
    returnRate: "2.2%",
    orders: 60,
    monthIncrease: "3%",
    yearIncrease: "9%",
  },
  {
    id: 9,
    name: "Ivy Gourd",
    sku: "IVG009",
    stock: 40,
    price: "4.99",
    returnRate: "2%",
    orders: 30,
    monthIncrease: "2%",
    yearIncrease: "11%",
  },
  {
    id: 10,
    name: "Jackfruit",
    sku: "JKF010",
    stock: 70,
    price: "1.49",
    returnRate: "3.5%",
    orders: 85,
    monthIncrease: "4%",
    yearIncrease: "14%",
  },
  {
    id: 11,
    name: "Kiwi",
    sku: "KIW011",
    stock: 120,
    price: "0.99",
    returnRate: "2%",
    orders: 150,
    monthIncrease: "5%",
    yearIncrease: "13%",
  },
  {
    id: 12,
    name: "Lemon",
    sku: "LEM012",
    stock: 160,
    price: "0.29",
    returnRate: "1%",
    orders: 200,
    monthIncrease: "3%",
    yearIncrease: "8%",
  },
  {
    id: 13,
    name: "Mango",
    sku: "MNG013",
    stock: 90,
    price: "0.79",
    returnRate: "2.5%",
    orders: 120,
    monthIncrease: "4%",
    yearIncrease: "12%",
  },
  {
    id: 14,
    name: "Nectarine",
    sku: "NCT014",
    stock: 110,
    price: "1.29",
    returnRate: "1.5%",
    orders: 95,
    monthIncrease: "2%",
    yearIncrease: "7%",
  },
  {
    id: 15,
    name: "Orange",
    sku: "ORG015",
    stock: 200,
    price: "0.59",
    returnRate: "1.8%",
    orders: 210,
    monthIncrease: "3%",
    yearIncrease: "9%",
  },
  {
    id: 16,
    name: "Papaya",
    sku: "PAP016",
    stock: 80,
    price: "1.99",
    returnRate: "3%",
    orders: 70,
    monthIncrease: "4%",
    yearIncrease: "10%",
  },
];
